//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyParkingSystem.Services.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TallyParkingSystem.Services.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Early Bird&quot;,
        ///    &quot;type&quot;: &quot;Flat Rate&quot;,
        ///    &quot;totalprice&quot;: 13,
        ///    &quot;entryperiod&quot;: &quot;6:00 - 9:00&quot;,
        ///    &quot;exitperiod&quot;: &quot;15:30 - 23:30&quot;,
        ///    &quot;weekend&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Night Rate&quot;,
        ///    &quot;type&quot;: &quot;Flat Rate&quot;,
        ///    &quot;totalprice&quot;: 6.50,
        ///    &quot;entryperiod&quot;: &quot;18:00 - 23:59&quot;,
        ///    &quot;exitperiod&quot;: &quot;00:00 - 05:59&quot;,
        ///    &quot;weekend&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Night Rate&quot;,
        ///    &quot;type&quot;: &quot;Flat Rate&quot;,
        ///    &quot;totalprice&quot;: 10,
        ///    &quot;entryperiod&quot;: &quot;00:00 - 23:59&quot;,
        ///    &quot;exitperiod&quot;: &quot;00:00 -  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string specialrates {
            get {
                return ResourceManager.GetString("specialrates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;Standard Rate&quot;,
        ///    &quot;type&quot;: &quot;Hourly Rate&quot;,
        ///    &quot;minimumhours&quot;: &quot;0&quot;,
        ///    &quot;maximumhours&quot;: &quot;1&quot;,
        ///    &quot;totalprice&quot;: 5,
        ///    &quot;flatrate&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Standard Rate&quot;,
        ///    &quot;type&quot;: &quot;Hourly Rate&quot;,
        ///    &quot;minimumhours&quot;: &quot;1&quot;,
        ///    &quot;maximumhours&quot;: &quot;2&quot;,
        ///    &quot;totalprice&quot;: 10,
        ///    &quot;flatrate&quot;: false
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;Standard Rate&quot;,
        ///    &quot;type&quot;: &quot;Hourly Rate&quot;,
        ///    &quot;minimumhours&quot;: &quot;2&quot;,
        ///    &quot;maximumhours&quot;: &quot;3&quot;,
        ///    &quot;totalprice&quot;: 15,
        ///    &quot;flatrate&quot;: false
        ///  },
        ///  {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string standardrates {
            get {
                return ResourceManager.GetString("standardrates", resourceCulture);
            }
        }
    }
}
